### ISSUE TITLE
Migrate to external Form Service

### ISSUE THREAD

**Issue by sdmcraft** [sunstar-engineering/sunstar-engineering#16]
The Helix Forms Service is deprecated, we should envision a migration away from it in the medium term. For B2B like this site Marketo might be a viable alternative or AEM Forms or a self-hosted forms service.

cc @jalagari

**Comment by ehrro** [comment]
Hello @sdmcraft we have Marketo in house. When is the deadline to move these away? Thank you.

**Comment by bosschaert** [comment]
As with sunstar-foundation the Helix 4 forms are migrated to use Power Automate.
